In [1]:
print("Welcome")

Welcome


In [2]:
import torch
torch.__version__



d:\NLP\venv\lib\site-packages\torch\_subclasses\functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.7.1+cpu'

In [3]:
a=torch.empty(2,3)
type(a)

torch.Tensor

In [4]:
a.fill_(2)
a

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [5]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.1889, 0.1155, 0.1050],
        [0.4941, 0.3132, 0.6811]])

In [8]:
torch.rand(2,3)

tensor([[0.1861, 0.4745, 0.4958],
        [0.9725, 0.6561, 0.1992]])

In [9]:
torch.rand(2,3)


tensor([[0.0587, 0.7353, 0.7984],
        [0.7109, 0.3847, 0.5248]])

In [10]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [11]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [12]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
torch.arange(1,10,5)

tensor([1, 6])

In [4]:
import torch
torch.linspace(0,1,20)

tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [17]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[2949476648816,             0,             0],
        [            0,             0,             0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

In [22]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [23]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [24]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [25]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [26]:
c=torch.tensor([1,-2,-3,-4])

In [27]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [28]:
torch.negative(c)

tensor([-1,  2,  3,  4])

In [29]:
d=torch.tensor([1.9,2.3,4.5,6.7])

In [30]:
torch.round(d)

tensor([2., 2., 4., 7.])

In [31]:
torch.floor(d)

tensor([1., 2., 4., 6.])

In [32]:
torch.ceil(d)

tensor([2., 3., 5., 7.])

In [33]:
e=torch.randint(size=(3,4),low=0,high=11,dtype=torch.float32)
e

tensor([[ 5.,  8.,  4.,  1.],
        [ 3.,  4.,  7.,  8.],
        [ 1., 10.,  2., 10.]])

In [34]:
torch.sum(e)

tensor(63.)

In [35]:
torch.sum(e,dim=0)

tensor([ 9., 22., 13., 19.])

In [36]:
torch.sum(e,dim=1)

tensor([18., 22., 23.])

In [37]:
torch.mean(e,dim=1)

tensor([4.5000, 5.5000, 5.7500])

In [38]:
torch.mean(e)

tensor(5.2500)

In [39]:
torch.min(e)

tensor(1.)

In [40]:
torch.max(e)

tensor(10.)

In [41]:
torch.argmax(e)

tensor(9)

argmax:it is giving me index of highest value in matrix

In [42]:
torch.argmin(e)

tensor(3)

argmin:it is giving me index of minium value in matrix

In [43]:
e

tensor([[ 5.,  8.,  4.,  1.],
        [ 3.,  4.,  7.,  8.],
        [ 1., 10.,  2., 10.]])

In [44]:
f=torch.randint(size=(2,3),low=0,high=10)
f

tensor([[9, 9, 4],
        [4, 9, 4]])

In [45]:
g=torch.randint(size=(3,2),low=0,high=10)
g

tensor([[4, 5],
        [4, 0],
        [8, 9]])

In [46]:
torch.matmul(f,g)

tensor([[104,  81],
        [ 84,  56]])

In [47]:
torch.matmul(g,f)

tensor([[ 56,  81,  36],
        [ 36,  36,  16],
        [108, 153,  68]])

In [48]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [49]:
vector1

tensor([1, 2])

In [50]:
vector2

tensor([3, 4])

In [51]:
torch.dot(vector1,vector2)

tensor(11)

In [52]:
torch.transpose(f,0,1)

tensor([[9, 4],
        [9, 9],
        [4, 4]])

In [53]:
torch.transpose(g,0,1)

tensor([[4, 4, 8],
        [5, 0, 9]])

In [54]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 0., 9.],
        [3., 7., 9.],
        [5., 2., 9.]])

In [55]:
torch.inverse(h)

tensor([[-0.3571, -0.1429,  0.5000],
        [-0.1429,  0.1429,  0.0000],
        [ 0.2302,  0.0476, -0.1667]])

In [56]:
torch.log(h)

tensor([[1.0986,   -inf, 2.1972],
        [1.0986, 1.9459, 2.1972],
        [1.6094, 0.6931, 2.1972]])

In [57]:
torch.exp(h)

tensor([[2.0086e+01, 1.0000e+00, 8.1031e+03],
        [2.0086e+01, 1.0966e+03, 8.1031e+03],
        [1.4841e+02, 7.3891e+00, 8.1031e+03]])

In [58]:
torch.softmax(h,0)

tensor([[1.0651e-01, 9.0496e-04, 3.3333e-01],
        [1.0651e-01, 9.9241e-01, 3.3333e-01],
        [7.8699e-01, 6.6868e-03, 3.3333e-01]])