In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

Tesla T4
cuda


In [ ]:
a = torch.empty(2,3)

In [ ]:
a

tensor([[3.6870e+27, 4.5317e-41, 3.6870e+27],
        [4.5317e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(3,4)

tensor([[0.4785, 0.1935, 0.2239, 0.5639],
        [0.6125, 0.2264, 0.5853, 0.1851],
        [0.4920, 0.7171, 0.4578, 0.3566]])

In [ ]:
torch.rand(3,4)

tensor([[0.4831, 0.6752, 0.2525, 0.5272],
        [0.8281, 0.4956, 0.8292, 0.0482],
        [0.0826, 0.2730, 0.7694, 0.8017]])

In [ ]:
torch.rand(3,4)

tensor([[0.1284, 0.6878, 0.4103, 0.6449],
        [0.9702, 0.0159, 0.5884, 0.8002],
        [0.5418, 0.2007, 0.4079, 0.3510]])

In [ ]:
torch.manual_seed(10)
torch.rand(3,4)


tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [ ]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [ ]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [ ]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [ ]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [ ]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.linspace(0,1,30)

tensor([0.0000, 0.0345, 0.0690, 0.1034, 0.1379, 0.1724, 0.2069, 0.2414, 0.2759,
        0.3103, 0.3448, 0.3793, 0.4138, 0.4483, 0.4828, 0.5172, 0.5517, 0.5862,
        0.6207, 0.6552, 0.6897, 0.7241, 0.7586, 0.7931, 0.8276, 0.8621, 0.8966,
        0.9310, 0.9655, 1.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[             275207,                  36,                   0],
        [                  0,                   0, 3919320687636068449]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [ ]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [ ]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [ ]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

In [ ]:
e

tensor([[8., 1., 8., 2.],
        [8., 9., 2., 3.],
        [1., 7., 0., 1.]])

In [ ]:
torch.sum(e)

tensor(50.)

In [ ]:
torch.sum(e, dim=0)

tensor([17., 17., 10.,  6.])

In [ ]:
torch.sum(e, dim=1)

tensor([19., 22.,  9.])

In [ ]:
torch.mean(e, dim=1)

tensor([4.7500, 5.5000, 2.2500])

In [ ]:
torch.mean(e)

tensor(4.1667)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
torch.max(e)

tensor(9.)

argmax it is giving me index of highest value in matrix

In [ ]:
torch.argmax(e)

tensor(5)

argmin it is giving me a index of minimum value in matrix

In [ ]:
torch.argmin(e)

tensor(10)

In [ ]:
e

tensor([[8., 1., 8., 2.],
        [8., 9., 2., 3.],
        [1., 7., 0., 1.]])

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [ ]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [ ]:
g

tensor([[3, 4],
        [0, 6],
        [9, 1]])

In [ ]:
2*3, 3*2 == 2*2

(6, False)

In [ ]:
torch.matmul(f,g)

tensor([[15, 56],
        [15, 38]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [ ]:
vector1

tensor([1, 2])

In [ ]:
vector2

tensor([3, 4])

In [ ]:
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [ ]:
torch.transpose(f,0,1)

tensor([[5, 5],
        [6, 3],
        [0, 0]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [ ]:
h

tensor([[8., 7., 9.],
        [8., 5., 1.],
        [2., 5., 7.]])

In [ ]:
torch.inverse(h)

tensor([[ 0.2273, -0.0303, -0.2879],
        [-0.4091,  0.2879,  0.4848],
        [ 0.2273, -0.1970, -0.1212]])

In [ ]:
torch.log(h)

tensor([[2.0794, 1.9459, 2.1972],
        [2.0794, 1.6094, 0.0000],
        [0.6931, 1.6094, 1.9459]])

In [ ]:
torch.exp(h)

tensor([[2.9810e+03, 1.0966e+03, 8.1031e+03],
        [2.9810e+03, 1.4841e+02, 2.7183e+00],
        [7.3891e+00, 1.4841e+02, 1.0966e+03]])

In [ ]:
torch.softmax(h,0)

tensor([[4.9938e-01, 7.8699e-01, 8.8054e-01],
        [4.9938e-01, 1.0651e-01, 2.9539e-04],
        [1.2378e-03, 1.0651e-01, 1.1917e-01]])

NN module
dataset and dataloader
gredient
training of nn on some data
transformer code

PyTorch makes **differentiation** (computing gradients) easy and efficient by providing the **autograd** package. This allows you to automatically compute the gradients of tensors during backpropagation, which is essential for training machine learning models, particularly in deep learning.

### Concept of autograd

### NN Module of Pytorch

### Dataset and Dataloader

In [ ]:
def dy_dx(x):
    return 2*x

In [ ]:
dy_dx(4)

8

In [ ]:
import torch
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2

In [ ]:
y=2*x

In [ ]:
y

tensor(6., grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(2.)

In [ ]:
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [ ]:
dz_dx(3)

-5.466781571308061

In [ ]:
dz_dx(5)

9.912028118634735

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2
z=torch.sin(y)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

![image.png](attachment:image.png)

In [ ]:
import torch.nn as nn

In [ ]:
class Model(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out


In [ ]:
data=torch.rand(10,5)

In [ ]:
data.shape

torch.Size([10, 5])

In [ ]:
data

tensor([[0.7171, 0.4578, 0.3566, 0.4831, 0.6752],
        [0.2525, 0.5272, 0.8281, 0.4956, 0.8292],
        [0.0482, 0.0826, 0.2730, 0.7694, 0.8017],
        [0.1284, 0.6878, 0.4103, 0.6449, 0.9702],
        [0.0159, 0.5884, 0.8002, 0.5418, 0.2007],
        [0.4079, 0.3510, 0.8876, 0.9466, 0.3037],
        [0.0089, 0.3416, 0.2241, 0.9258, 0.9720],
        [0.7581, 0.4573, 0.0179, 0.5359, 0.3075],
        [0.5056, 0.2659, 0.4479, 0.7825, 0.9937],
        [0.9111, 0.2280, 0.8256, 0.8253, 0.7007]])

In [ ]:
[0.9362, 0.8712, 0.2160, 0.4761, 0.0445]
[0.8966, 0.6267, 0.6745, 0.2108, 0.1460]/open(file, mode)


NameError: name 'file' is not defined

In [ ]:
model=Model(data.shape[1])

In [ ]:
model(data)


tensor([[0.3522],
        [0.3714],
        [0.3700],
        [0.3816],
        [0.3954],
        [0.3248],
        [0.3646],
        [0.3589],
        [0.3327],
        [0.2947]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.forward(data)

tensor([[0.3522],
        [0.3714],
        [0.3700],
        [0.3816],
        [0.3954],
        [0.3248],
        [0.3646],
        [0.3589],
        [0.3327],
        [0.2947]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.3158,  0.0924, -0.1208, -0.3585, -0.0547]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1720], requires_grad=True)

In [ ]:
class test:
    def __init__(self):
        print("hello from init")
    def __call__(self):
        print("hello from call")
    def testing(self):
        print("hello from testing")

In [ ]:
obj=test()

hello from init


In [ ]:
obj.testing()

hello from testing


In [ ]:
obj()

hello from call


![image.png](attachment:image.png)

In [ ]:
class Model(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [ ]:
data=torch.rand(10,5)

In [ ]:
data

tensor([[0.9463, 0.2603, 0.9883, 0.7877, 0.9897],
        [0.4981, 0.4836, 0.0749, 0.6935, 0.8236],
        [0.4538, 0.4841, 0.4648, 0.7601, 0.2106],
        [0.4811, 0.5939, 0.7097, 0.9335, 0.0694],
        [0.5998, 0.6074, 0.2894, 0.4070, 0.3847],
        [0.1057, 0.0974, 0.4719, 0.8269, 0.9927],
        [0.5702, 0.1573, 0.3421, 0.5972, 0.6178],
        [0.5778, 0.3057, 0.6116, 0.9337, 0.1543],
        [0.3581, 0.2005, 0.2940, 0.9519, 0.7251],
        [0.4703, 0.4832, 0.9063, 0.6593, 0.4455]])

In [ ]:
data.shape

torch.Size([10, 5])

In [ ]:
data.shape[1]

5

In [ ]:
model=Model(data.shape[1])

In [ ]:
model(data)

tensor([[0.5489],
        [0.5191],
        [0.5523],
        [0.5688],
        [0.5215],
        [0.5383],
        [0.5368],
        [0.5719],
        [0.5479],
        [0.5501]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1338, -0.0648,  0.0359, -0.2881, -0.1811],
        [-0.3487,  0.2594, -0.2045,  0.0469, -0.2403],
        [ 0.0416, -0.2168,  0.1947,  0.4101, -0.2687]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.3798,  0.0377,  0.3600], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5611, -0.3546,  0.5015]], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.1009], requires_grad=True)

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
data=torch.rand(10,5)

In [ ]:
model=Model(data.shape[1])

In [ ]:
model.forward(data)

tensor([[0.5550],
        [0.5334],
        [0.5863],
        [0.5444],
        [0.5614],
        [0.5765],
        [0.5490],
        [0.5771],
        [0.5348],
        [0.5710]], grad_fn=<SigmoidBackward0>)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary


In [ ]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       18
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
data=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [ ]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
data.shape

(569, 33)

In [ ]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [ ]:
data.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Benign= no cancer

### malignant=cancer


In [ ]:
data["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
data.iloc[:, 0]

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [ ]:
data.iloc[:, 1:]

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size=0.2)

In [ ]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
337        18.77         21.43          122.90     1092.0          0.09116   
530        11.75         17.56           75.89      422.9          0.10730   
519        12.75         16.70           82.51      493.8          0.11250   
142        11.43         17.31           73.66      398.0          0.10920   
356        13.05         18.59           85.09      512.0          0.10820   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
337           0.14020         0.10600              0.06090         0.1953   
530           0.09713         0.05282              0.04440         0.1598   
519           0.11170         0.03880              0.02995         0.2120   
142           0.09486         0.02031              0.01861         0.1645   
356           0.13040         0.09603              0.05603         0.2035   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
337                 0.06083  ...         24.54          34.37   
530                 0.06677  ...         13.50          27.98   
519                 0.06623  ...         14.45          21.74   
142                 0.06562  ...         12.78          26.76   
356                 0.06501  ...         14.19          24.85   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
337           161.10      1873.0            0.1498             0.4827   
530            88.52       552.3            0.1349             0.1854   
519            93.63       624.1            0.1475             0.1979   
142            82.66       503.0            0.1413             0.1792   
356            94.22       591.2            0.1343             0.2658   

     concavity_worst  concave points_worst  symmetry_worst  \
337          0.46340               0.20480          0.3679   
530          0.13660               0.10100          0.2478   
519          0.14230               0.08045          0.3071   
142          0.07708               0.06402          0.2584   
356          0.25730               0.12580          0.3113   

     fractal_dimension_worst  
337                  0.09870  
530                  0.07757  
519                  0.08557  
142                  0.08096  
356                  0.08317  

[5 rows x 30 columns]

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train

array([[ 1.22593842,  0.50807899,  1.18488779, ...,  1.32819845,
         1.20818436,  0.79687737],
       [-0.70881272, -0.41600394, -0.69453453, ..., -0.24402232,
        -0.7101573 , -0.34109868],
       [-0.43320714, -0.6213557 , -0.4298722 , ..., -0.55528568,
         0.23703388,  0.08974886],
       ...,
       [ 0.31368397, -1.76989287,  0.36931206, ...,  0.99345781,
         0.46864049,  0.92074604],
       [ 0.3550248 ,  0.0185777 ,  0.26936405, ..., -0.47606878,
        -0.38271347, -0.84088182],
       [ 0.22273413,  2.50906475,  0.13783247, ..., -0.77794122,
         0.49579437, -1.19848528]])

In [ ]:
X_test

array([[-0.82732311,  1.8571923 , -0.85964863, ..., -1.45832809,
        -0.11756383, -0.70193349],
       [-0.15760157,  1.0668268 , -0.18879761, ..., -0.84897894,
        -0.41465921, -1.11447001],
       [-0.28162407,  0.54150834, -0.32072898, ..., -0.92350039,
        -0.45618867, -0.93297548],
       ...,
       [ 1.07435536, -0.10320067,  1.01697514, ...,  0.91620997,
        -0.17666345, -0.10359398],
       [ 1.44091077,  2.26073239,  1.61266526, ...,  1.16612945,
        -0.16707973,  0.89381807],
       [-0.18240607, -0.99146643, -0.199592  , ..., -0.17737712,
         0.74177656,  0.67193159]])

In [ ]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,

In [ ]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0])

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.dtype

torch.float32

In [ ]:
type(X_train_tensor)

torch.Tensor

In [ ]:
class MySimpleNN(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [ ]:
data.shape

(569, 31)

In [ ]:
X_train.shape[1]

30

In [ ]:
learning_rate=0.01
epochs=25

In [ ]:
loss_function=nn.BCELoss()

In [ ]:
model=MySimpleNN(X_train.shape[1])

optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [ ]:
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients in back propagation
    optimizer.zero_grad()

    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6606467962265015
Epoch: 2, Loss: 0.6593907475471497
Epoch: 3, Loss: 0.6581447124481201
Epoch: 4, Loss: 0.6569046378135681
Epoch: 5, Loss: 0.6556737422943115
Epoch: 6, Loss: 0.6544394493103027
Epoch: 7, Loss: 0.6532099843025208
Epoch: 8, Loss: 0.6519821286201477
Epoch: 9, Loss: 0.6507643461227417
Epoch: 10, Loss: 0.6495620012283325
Epoch: 11, Loss: 0.6483701467514038
Epoch: 12, Loss: 0.6471813917160034
Epoch: 13, Loss: 0.6460094451904297
Epoch: 14, Loss: 0.6448472142219543
Epoch: 15, Loss: 0.6436916589736938
Epoch: 16, Loss: 0.6425358653068542
Epoch: 17, Loss: 0.6413857936859131
Epoch: 18, Loss: 0.6402522325515747
Epoch: 19, Loss: 0.6391265392303467
Epoch: 20, Loss: 0.6379979848861694
Epoch: 21, Loss: 0.6368736624717712
Epoch: 22, Loss: 0.6357670426368713
Epoch: 23, Loss: 0.6346578598022461
Epoch: 24, Loss: 0.6335527896881104
Epoch: 25, Loss: 0.6324455738067627


In [ ]:
X_test_tensor.shape

torch.Size([114, 30])

In [ ]:
X_test_tensor[1]

tensor([-0.1576,  1.0668, -0.1888, -0.2304, -1.1170, -0.6879, -0.5388, -0.6683,
        -0.1340, -1.1584,  0.0787, -0.2794, -0.0382, -0.0459, -0.9514,  0.0723,
         0.0451, -0.2785,  0.6151, -0.2477, -0.3076,  0.0904, -0.3204, -0.3482,
        -1.7413, -0.7107, -0.6767, -0.8490, -0.4147, -1.1145])

In [ ]:
model.forward(X_test_tensor[1])

tensor([0.4107], grad_fn=<SigmoidBackward0>)

In [ ]:
y_pred=model.forward(X_test_tensor[1])

In [ ]:
y_pred

tensor([0.4107], grad_fn=<SigmoidBackward0>)

In [ ]:
y_pred=(y_pred>0.5).float()

In [ ]:
y_test_tensor=y_test_tensor[0]

In [ ]:
(y_pred==y_test_tensor).float()

tensor([1.])

In [ ]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')



Accuracy: 0.8070175647735596


In [ ]:
summary(model)

Layer (type:depth-idx)                   Param #
MySimpleNN                               --
├─Linear: 1-1                            93
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 97
Trainable params: 97
Non-trainable params: 0

## DataLoader and Dataset

In [ ]:
from sklearn.datasets import make_classification
import torch

In [ ]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [ ]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [ ]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataSet(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [ ]:
dataset=CustomDataSet(X,y)

In [ ]:
len(dataset)

10

In [ ]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [ ]:
dataset[9]

(tensor([-0.5872, -1.9717]), tensor(0))

In [ ]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=False)

In [ ]:
dataloader

In [ ]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


1. load the sentiment analysis data(test.csv)
data: https://www.kaggle.com/datasets/abhi8923shriv/sentiment-analysis-dataset?select=test.csv
2. you have to perform some preprocessing
3. there should be two columns(text,sentiment)
4. then perform text encoding or embedding over the text data and label encoding on target column
5. write a rnn code in pytorch from scratch to train sentiment analysis model on batch data using dataset and dataloader
6. then test it out on random example